# Generated by Django 5.2.1 on 2025-05-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadhistory',
            options={'ordering': ['-timestamp']},
        ),
    ]
