# Generated by Django 5.2.1 on 2025-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_uploadhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='detection_details',
            field=models.JSONField(default=dict),
        ),
    ]
